/**
 * This class is generated by jOOQ
 */
package jp.scid.bio.store.jooq;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all sequences in PUBLIC
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.6.0"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings("all")
public final class Sequences {

	/**
	 * The sequence PUBLIC.SYSTEM_SEQUENCE_1E5901A4_03C0_4DD1_9178_24C38C91C8CB
	 */
	public static final org.jooq.Sequence<java.lang.Long> SYSTEM_SEQUENCE_1E5901A4_03C0_4DD1_9178_24C38C91C8CB = new org.jooq.impl.SequenceImpl<java.lang.Long>("SYSTEM_SEQUENCE_1E5901A4_03C0_4DD1_9178_24C38C91C8CB", jp.scid.bio.store.jooq.Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);

	/**
	 * The sequence PUBLIC.SYSTEM_SEQUENCE_DF316686_0F8C_4436_8429_F5605D545300
	 */
	public static final org.jooq.Sequence<java.lang.Long> SYSTEM_SEQUENCE_DF316686_0F8C_4436_8429_F5605D545300 = new org.jooq.impl.SequenceImpl<java.lang.Long>("SYSTEM_SEQUENCE_DF316686_0F8C_4436_8429_F5605D545300", jp.scid.bio.store.jooq.Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);

	/**
	 * The sequence PUBLIC.SYSTEM_SEQUENCE_E4025641_F835_49F6_82B4_CECEC9FF9823
	 */
	public static final org.jooq.Sequence<java.lang.Long> SYSTEM_SEQUENCE_E4025641_F835_49F6_82B4_CECEC9FF9823 = new org.jooq.impl.SequenceImpl<java.lang.Long>("SYSTEM_SEQUENCE_E4025641_F835_49F6_82B4_CECEC9FF9823", jp.scid.bio.store.jooq.Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);

	/**
	 * No instances
	 */
	private Sequences() {}
}
