/**
 * This class is generated by jOOQ
 */
package jp.scid.bio.store.jooq;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all sequences in PUBLIC
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.6.0"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings("all")
public final class Sequences {

	/**
	 * The sequence PUBLIC.SYSTEM_SEQUENCE_13FD907B_C6AB_4E31_9636_9E9A111139B0
	 */
	public static final org.jooq.Sequence<java.lang.Long> SYSTEM_SEQUENCE_13FD907B_C6AB_4E31_9636_9E9A111139B0 = new org.jooq.impl.SequenceImpl<java.lang.Long>("SYSTEM_SEQUENCE_13FD907B_C6AB_4E31_9636_9E9A111139B0", jp.scid.bio.store.jooq.Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);

	/**
	 * No instances
	 */
	private Sequences() {}
}
