/**
 * This class is generated by jOOQ
 */
package jp.scid.bio.store.jooq;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in PUBLIC
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.6.0"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings("all")
public final class Tables {

	/**
	 * 配列 : バイオデータファイルを表すテーブル
	 */
	public static final jp.scid.bio.store.jooq.tables.GeneticSequence GENETIC_SEQUENCE = jp.scid.bio.store.jooq.tables.GeneticSequence.GENETIC_SEQUENCE;

	/**
	 * No instances
	 */
	private Tables() {}
}
