/**
 * This class is generated by jOOQ
 */
package jp.scid.bio.store.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 *
 * 配列コレクション
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.6.0"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings("all")
public class CollectionItemRecord extends org.jooq.impl.UpdatableRecordImpl<jp.scid.bio.store.jooq.tables.records.CollectionItemRecord> {

	private static final long serialVersionUID = -699468997;

	/**
	 * 識別子
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public void setId(java.lang.Long value) {
		setValue(jp.scid.bio.store.jooq.tables.CollectionItem.COLLECTION_ITEM.ID, value);
	}

	/**
	 * 識別子
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public java.lang.Long getId() {
		return getValue(jp.scid.bio.store.jooq.tables.CollectionItem.COLLECTION_ITEM.ID);
	}

	/**
	 * フォルダ id
	 * <p>
	 * This column is part of a FOREIGN KEY: <code><pre>
	 * CONSTRAINT FK_COLLECTION_ITEM_FOLDER_ID
	 * FOREIGN KEY (FOLDER_ID, FOLDER_ID)
	 * REFERENCES PUBLIC.FOLDER (ID)
	 * </pre></code>
	 */
	public void setFolderId(java.lang.Long value) {
		setValue(jp.scid.bio.store.jooq.tables.CollectionItem.COLLECTION_ITEM.FOLDER_ID, value);
	}

	/**
	 * フォルダ id
	 * <p>
	 * This column is part of a FOREIGN KEY: <code><pre>
	 * CONSTRAINT FK_COLLECTION_ITEM_FOLDER_ID
	 * FOREIGN KEY (FOLDER_ID, FOLDER_ID)
	 * REFERENCES PUBLIC.FOLDER (ID)
	 * </pre></code>
	 */
	public java.lang.Long getFolderId() {
		return getValue(jp.scid.bio.store.jooq.tables.CollectionItem.COLLECTION_ITEM.FOLDER_ID);
	}

	/**
	 * 配列識別子
	 * <p>
	 * This column is part of a FOREIGN KEY: <code><pre>
	 * CONSTRAINT FK_COLLECTION_ITEM_GENETIC_SEQUENCE_ID
	 * FOREIGN KEY (GENETIC_SEQUENCE_ID)
	 * REFERENCES PUBLIC.GENETIC_SEQUENCE (ID)
	 * </pre></code>
	 */
	public void setGeneticSequenceId(java.lang.Long value) {
		setValue(jp.scid.bio.store.jooq.tables.CollectionItem.COLLECTION_ITEM.GENETIC_SEQUENCE_ID, value);
	}

	/**
	 * 配列識別子
	 * <p>
	 * This column is part of a FOREIGN KEY: <code><pre>
	 * CONSTRAINT FK_COLLECTION_ITEM_GENETIC_SEQUENCE_ID
	 * FOREIGN KEY (GENETIC_SEQUENCE_ID)
	 * REFERENCES PUBLIC.GENETIC_SEQUENCE (ID)
	 * </pre></code>
	 */
	public java.lang.Long getGeneticSequenceId() {
		return getValue(jp.scid.bio.store.jooq.tables.CollectionItem.COLLECTION_ITEM.GENETIC_SEQUENCE_ID);
	}

	/**
	 * Link this record to a given {@link jp.scid.bio.store.jooq.tables.records.GeneticSequenceRecord 
	 * GeneticSequenceRecord}
	 */
	public void setGeneticSequenceId(jp.scid.bio.store.jooq.tables.records.GeneticSequenceRecord value) {
		if (value == null) {
			setValue(jp.scid.bio.store.jooq.tables.CollectionItem.COLLECTION_ITEM.GENETIC_SEQUENCE_ID, null);
		}
		else {
			setValue(jp.scid.bio.store.jooq.tables.CollectionItem.COLLECTION_ITEM.GENETIC_SEQUENCE_ID, value.getValue(jp.scid.bio.store.jooq.tables.GeneticSequence.GENETIC_SEQUENCE.ID));
		}
	}

	/**
	 * 配列識別子
	 * <p>
	 * This column is part of a FOREIGN KEY: <code><pre>
	 * CONSTRAINT FK_COLLECTION_ITEM_GENETIC_SEQUENCE_ID
	 * FOREIGN KEY (GENETIC_SEQUENCE_ID)
	 * REFERENCES PUBLIC.GENETIC_SEQUENCE (ID)
	 * </pre></code>
	 */
	public jp.scid.bio.store.jooq.tables.records.GeneticSequenceRecord fetchGeneticSequence() {
		return create()
			.selectFrom(jp.scid.bio.store.jooq.tables.GeneticSequence.GENETIC_SEQUENCE)
			.where(jp.scid.bio.store.jooq.tables.GeneticSequence.GENETIC_SEQUENCE.ID.equal(getValue(jp.scid.bio.store.jooq.tables.CollectionItem.COLLECTION_ITEM.GENETIC_SEQUENCE_ID)))
			.fetchOne();
	}

	/**
	 * Create a detached CollectionItemRecord
	 */
	public CollectionItemRecord() {
		super(jp.scid.bio.store.jooq.tables.CollectionItem.COLLECTION_ITEM);
	}
}
