/**
 * This class is generated by jOOQ
 */
package jp.scid.bio.store.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 *
 * フォルダ : フォルダとその階層構造
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.6.0"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings("all")
public class FolderRecord extends org.jooq.impl.UpdatableRecordImpl<jp.scid.bio.store.jooq.tables.records.FolderRecord> {

	private static final long serialVersionUID = -1207512851;

	/**
	 * 識別子
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public void setId(java.lang.Long value) {
		setValue(jp.scid.bio.store.jooq.tables.Folder.FOLDER.ID, value);
	}

	/**
	 * 識別子
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public java.lang.Long getId() {
		return getValue(jp.scid.bio.store.jooq.tables.Folder.FOLDER.ID);
	}

	/**
	 * 親の識別子
	 * <p>
	 * This column is part of a FOREIGN KEY: <code><pre>
	 * CONSTRAINT FK_FOLDER_PARENT
	 * FOREIGN KEY (PARENT_ID, PARENT_ID)
	 * REFERENCES PUBLIC.FOLDER (ID)
	 * </pre></code>
	 */
	public void setParentId(java.lang.Long value) {
		setValue(jp.scid.bio.store.jooq.tables.Folder.FOLDER.PARENT_ID, value);
	}

	/**
	 * 親の識別子
	 * <p>
	 * This column is part of a FOREIGN KEY: <code><pre>
	 * CONSTRAINT FK_FOLDER_PARENT
	 * FOREIGN KEY (PARENT_ID, PARENT_ID)
	 * REFERENCES PUBLIC.FOLDER (ID)
	 * </pre></code>
	 */
	public java.lang.Long getParentId() {
		return getValue(jp.scid.bio.store.jooq.tables.Folder.FOLDER.PARENT_ID);
	}

	/**
	 * 名前
	 */
	public void setName(java.lang.String value) {
		setValue(jp.scid.bio.store.jooq.tables.Folder.FOLDER.NAME, value);
	}

	/**
	 * 名前
	 */
	public java.lang.String getName() {
		return getValue(jp.scid.bio.store.jooq.tables.Folder.FOLDER.NAME);
	}

	/**
	 * 構造型 : 0: 階層, 1: コレクション, 2: フィルター
	 */
	public void setType(java.lang.Short value) {
		setValue(jp.scid.bio.store.jooq.tables.Folder.FOLDER.TYPE, value);
	}

	/**
	 * 構造型 : 0: 階層, 1: コレクション, 2: フィルター
	 */
	public java.lang.Short getType() {
		return getValue(jp.scid.bio.store.jooq.tables.Folder.FOLDER.TYPE);
	}

	/**
	 * Create a detached FolderRecord
	 */
	public FolderRecord() {
		super(jp.scid.bio.store.jooq.tables.Folder.FOLDER);
	}
}
